spring.application.name=hazelcast-vector-store-example

spring.ai.vectorstore.hazelcast.initialize-schema=true
spring.ai.vectorstore.hazelcast.collection-name=example-documents
spring.ai.vectorstore.hazelcast.index-name=example-index
spring.ai.vectorstore.hazelcast.metric=COSINE

logging.level.com.hazelcast=warn
